title: Acervo Cc ğŸ–¥ï¸
description: Acervo de projetos, provas e outros materiais acadÃªmicos durante o curso de CiÃªncia da ComputaÃ§Ã£o ğŸ“
theme: just-the-docs

url: https://LucasWithBoots.github.io/unifal-cc-acervo/

color_scheme: dark

favicon_ico: "/assets/images/favicon.ico"

callouts:
  aviso:
    title: Aviso
    color: red
  importante:
    title: Importante
    color: blue

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

nav_external_links:
  - title: Acervo no GitHub
    url: https://github.com/LucasWithBoots/unifal-cc-acervo
    hide_icon: false
    opens_in_new_tab: true
